services:
  # Service 1: The Main Application (API)
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        user: laravel
        uid: 1000
    image: spectraflow-app
    container_name: spectraflow_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - spectra-network
    depends_on:
      - db
      - redis

  # Service 2: The Queue Worker (Background Processor)
  # Critical for 'SpectraFlow' - this runs the scrapers asynchronously
  queue:
    image: spectraflow-app
    container_name: spectraflow_worker
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan queue:work --tries=3 --timeout=120 -v
    volumes:
      - ./backend:/var/www/html
      - ./scraper:/var/www/scraper
    networks:
      - spectra-network
    depends_on:
      - app
      - redis
      - db

  # Service 3: The Web Server
  web:
    image: nginx:alpine
    container_name: spectraflow_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - spectra-network
    depends_on:
      - app

  # Service 4: The Database (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: spectraflow_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: spectraflow
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432" # Exposed so you can check data with TablePlus/DBeaver
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spectra-network

  # Service 5: Cache & Queue Driver (Redis)
  redis:
    image: redis:alpine
    container_name: spectraflow_redis
    restart: unless-stopped
    networks:
      - spectra-network

networks:
  spectra-network:
    driver: bridge

volumes:
  pgdata: